# Generated by Django 4.0.5 on 2022-07-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='pics')),
                ('available', models.BooleanField(default='True')),
                ('content', models.FileField(null=True, upload_to='pdfs', verbose_name=' ')),
            ],
        ),
    ]
