# Generated by Django 4.0.5 on 2022-07-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_author_book_genre_bookinstance_book_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
